/* Resource Datei Indizes fÅr AVALON */

#define DIALOG1          0   /* Formular/Dialog */
#define DESKFIRS         0   /* BOX in Baum DIALOG1 */
#define NOTEBOOK         1   /* IMAGE in Baum DIALOG1 */
#define DONOTE           2   /* IMAGE in Baum DIALOG1 */
#define STARTSEL         3   /* BOXTEXT in Baum DIALOG1 */
#define DOPROGS          4   /* BOXTEXT in Baum DIALOG1 */
#define TBOX2            5   /* BOXTEXT in Baum DIALOG1 */
#define DESKSESS         6   /* IBOX in Baum DIALOG1 */
#define START1           7   /* BOXTEXT in Baum DIALOG1 */
#define AUTO1            8   /* BOXTEXT in Baum DIALOG1 */
#define START2           9   /* BOXTEXT in Baum DIALOG1 */
#define AUTO2            10  /* BOXTEXT in Baum DIALOG1 */
#define START3           11  /* BOXTEXT in Baum DIALOG1 */
#define AUTO3            12  /* BOXTEXT in Baum DIALOG1 */
#define START4           13  /* BOXTEXT in Baum DIALOG1 */
#define AUTO4            14  /* BOXTEXT in Baum DIALOG1 */
#define START5           15  /* BOXTEXT in Baum DIALOG1 */
#define AUTO5            16  /* BOXTEXT in Baum DIALOG1 */
#define START6           17  /* BOXTEXT in Baum DIALOG1 */
#define AUTO6            18  /* BOXTEXT in Baum DIALOG1 */
#define DESKPRGS         19  /* IBOX in Baum DIALOG1 */
#define DOIMPORT         20  /* BOXTEXT in Baum DIALOG1 */
#define DOUTIL1          21  /* BOXTEXT in Baum DIALOG1 */
#define DOAPP            22  /* BOXTEXT in Baum DIALOG1 */
#define DOEXPORT         23  /* BOXTEXT in Baum DIALOG1 */
#define DOUTIL2          24  /* BOXTEXT in Baum DIALOG1 */
#define DOPRG            25  /* BOXTEXT in Baum DIALOG1 */
#define DOCRUNCH         26  /* BOXTEXT in Baum DIALOG1 */
#define DOUTIL3          27  /* BOXTEXT in Baum DIALOG1 */
#define DOTOS            28  /* BOXTEXT in Baum DIALOG1 */
#define DOSCAN           29  /* BOXTEXT in Baum DIALOG1 */
#define DOUTIL4          30  /* BOXTEXT in Baum DIALOG1 */
#define DOTTP            31  /* BOXTEXT in Baum DIALOG1 */
#define DOTERM           32  /* BOXTEXT in Baum DIALOG1 */
#define DOUTIL5          33  /* BOXTEXT in Baum DIALOG1 */
#define DOALL            34  /* BOXTEXT in Baum DIALOG1 */
#define DOMAILER         35  /* BOXTEXT in Baum DIALOG1 */
#define DOUTIL6          36  /* BOXTEXT in Baum DIALOG1 */
#define DOSTAR           37  /* BOXTEXT in Baum DIALOG1 */
#define DESKPNT          38  /* IBOX in Baum DIALOG1 */
#define POINT0           39  /* BOXTEXT in Baum DIALOG1 */
#define POINT1           40  /* BOXTEXT in Baum DIALOG1 */
#define POINT2           41  /* BOXTEXT in Baum DIALOG1 */
#define POINT3           42  /* BOXTEXT in Baum DIALOG1 */
#define POINT4           43  /* BOXTEXT in Baum DIALOG1 */
#define POINT5           44  /* BOXTEXT in Baum DIALOG1 */
#define DOMSGED          45  /* BOXTEXT in Baum DIALOG1 */
#define DOTXTED          46  /* BOXTEXT in Baum DIALOG1 */
#define DOFREQ           47  /* BOXTEXT in Baum DIALOG1 */
#define DOSETUP1         49  /* BOXTEXT in Baum DIALOG1 */
#define DOSPEZIA         50  /* BOXTEXT in Baum DIALOG1 */
#define DOSETUP2         51  /* BOXTEXT in Baum DIALOG1 */
#define DOSETUP3         52  /* BOXTEXT in Baum DIALOG1 */
#define DOAREAS          53  /* BOXTEXT in Baum DIALOG1 */
#define DSAVE            54  /* BOXTEXT in Baum DIALOG1 */
#define DMANAGER         55  /* BOXTEXT in Baum DIALOG1 */
#define DOQUIT           56  /* BOXTEXT in Baum DIALOG1 */
#define DOFIX            57  /* BOXTEXT in Baum DIALOG1 */
#define DOHATCH          58  /* BOXTEXT in Baum DIALOG1 */
#define TBOX             59  /* BOX in Baum DIALOG1 */
#define BT3001           60  /* TEXT in Baum DIALOG1 */
#define BT3002           61  /* TEXT in Baum DIALOG1 */
#define BT3003           62  /* TEXT in Baum DIALOG1 */
#define BT3004           63  /* TEXT in Baum DIALOG1 */
#define BT3005           64  /* TEXT in Baum DIALOG1 */
#define BT3006           65  /* TEXT in Baum DIALOG1 */
#define BT3007           66  /* TEXT in Baum DIALOG1 */
#define BT3008           67  /* TEXT in Baum DIALOG1 */
#define BT3009           68  /* TEXT in Baum DIALOG1 */
#define BT300A           69  /* TEXT in Baum DIALOG1 */
#define BT300B           70  /* TEXT in Baum DIALOG1 */
#define BT300C           71  /* TEXT in Baum DIALOG1 */
#define TLOGO            72  /* BOX in Baum DIALOG1 */
#define AVALLOGO         74  /* IMAGE in Baum DIALOG1 */
#define DESKINFO         80  /* BOX in Baum DIALOG1 */
#define DOTIME           81  /* BOXTEXT in Baum DIALOG1 */
#define DOINFO           82  /* BOXTEXT in Baum DIALOG1 */
#define DODATE           83  /* BOXTEXT in Baum DIALOG1 */

#define DIALOG2          1   /* Formular/Dialog */
#define SESSION1         3   /* BUTTON in Baum DIALOG2 */
#define SESSION2         4   /* BUTTON in Baum DIALOG2 */
#define SESSION3         5   /* BUTTON in Baum DIALOG2 */
#define SESSION4         6   /* BUTTON in Baum DIALOG2 */
#define SESSION5         7   /* BUTTON in Baum DIALOG2 */
#define SESSION6         8   /* BUTTON in Baum DIALOG2 */
#define XIMPORT          12  /* BOXTEXT in Baum DIALOG2 */
#define XUTIL1           13  /* BOXTEXT in Baum DIALOG2 */
#define XEXPORT          14  /* BOXTEXT in Baum DIALOG2 */
#define XUTIL2           15  /* BOXTEXT in Baum DIALOG2 */
#define XCRUNCH          16  /* BOXTEXT in Baum DIALOG2 */
#define XUTIL3           17  /* BOXTEXT in Baum DIALOG2 */
#define XSCANNER         18  /* BOXTEXT in Baum DIALOG2 */
#define XUTIL4           19  /* BOXTEXT in Baum DIALOG2 */
#define XMSGED           20  /* BOXTEXT in Baum DIALOG2 */
#define XUTIL5           21  /* BOXTEXT in Baum DIALOG2 */
#define XMAILER          22  /* BOXTEXT in Baum DIALOG2 */
#define XUTIL6           23  /* BOXTEXT in Baum DIALOG2 */
#define XTERM            24  /* BOXTEXT in Baum DIALOG2 */
#define XOTHER           25  /* BOXTEXT in Baum DIALOG2 */
#define XBATCH           26  /* BOXTEXT in Baum DIALOG2 */
#define XBOX             32  /* BOX in Baum DIALOG2 */
#define XPROG1           33  /* FTEXT in Baum DIALOG2 */
#define XPROG2           34  /* FTEXT in Baum DIALOG2 */
#define XPROG3           35  /* FTEXT in Baum DIALOG2 */
#define XPROG4           36  /* FTEXT in Baum DIALOG2 */
#define XPROG5           37  /* FTEXT in Baum DIALOG2 */
#define XPROG6           38  /* FTEXT in Baum DIALOG2 */
#define XPROG7           39  /* FTEXT in Baum DIALOG2 */
#define XPROG8           40  /* FTEXT in Baum DIALOG2 */
#define XPROG9           41  /* FTEXT in Baum DIALOG2 */
#define XPROG10          42  /* FTEXT in Baum DIALOG2 */
#define XPROG11          43  /* FTEXT in Baum DIALOG2 */
#define XPROG12          44  /* FTEXT in Baum DIALOG2 */
#define XBOX3            45  /* IBOX in Baum DIALOG2 */
#define XWAIT1           46  /* BOX in Baum DIALOG2 */
#define XWAIT2           47  /* BOX in Baum DIALOG2 */
#define XWAIT3           48  /* BOX in Baum DIALOG2 */
#define XWAIT4           49  /* BOX in Baum DIALOG2 */
#define XWAIT5           50  /* BOX in Baum DIALOG2 */
#define XWAIT6           51  /* BOX in Baum DIALOG2 */
#define XWAIT7           52  /* BOX in Baum DIALOG2 */
#define XWAIT8           53  /* BOX in Baum DIALOG2 */
#define XWAIT9           54  /* BOX in Baum DIALOG2 */
#define XWAIT10          55  /* BOX in Baum DIALOG2 */
#define XWAIT11          56  /* BOX in Baum DIALOG2 */
#define XWAIT12          57  /* BOX in Baum DIALOG2 */
#define XRED1            58  /* BOX in Baum DIALOG2 */
#define XRED2            59  /* BOX in Baum DIALOG2 */
#define XRED3            60  /* BOX in Baum DIALOG2 */
#define XRED4            61  /* BOX in Baum DIALOG2 */
#define XRED5            62  /* BOX in Baum DIALOG2 */
#define XRED6            63  /* BOX in Baum DIALOG2 */
#define XRED7            64  /* BOX in Baum DIALOG2 */
#define XRED8            65  /* BOX in Baum DIALOG2 */
#define XRED9            66  /* BOX in Baum DIALOG2 */
#define XRED10           67  /* BOX in Baum DIALOG2 */
#define XRED11           68  /* BOX in Baum DIALOG2 */
#define XRED12           69  /* BOX in Baum DIALOG2 */
#define XERR1            70  /* FTEXT in Baum DIALOG2 */
#define XERR2            71  /* FTEXT in Baum DIALOG2 */
#define XERR3            72  /* FTEXT in Baum DIALOG2 */
#define XERR4            73  /* FTEXT in Baum DIALOG2 */
#define XERR5            74  /* FTEXT in Baum DIALOG2 */
#define XERR6            75  /* FTEXT in Baum DIALOG2 */
#define XERR7            76  /* FTEXT in Baum DIALOG2 */
#define XERR8            77  /* FTEXT in Baum DIALOG2 */
#define XERR9            78  /* FTEXT in Baum DIALOG2 */
#define XERR10           79  /* FTEXT in Baum DIALOG2 */
#define XERR11           80  /* FTEXT in Baum DIALOG2 */
#define XERR12           81  /* FTEXT in Baum DIALOG2 */
#define XBOX1            82  /* IBOX in Baum DIALOG2 */
#define XMAIN            83  /* BOXTEXT in Baum DIALOG2 */
#define XSET1            84  /* BOXTEXT in Baum DIALOG2 */
#define XSET2            85  /* BOXTEXT in Baum DIALOG2 */
#define XSET3            86  /* BOXTEXT in Baum DIALOG2 */
#define XSET4            87  /* BOXTEXT in Baum DIALOG2 */
#define XSET5            88  /* BOXTEXT in Baum DIALOG2 */
#define XSETNO           89  /* BOXTEXT in Baum DIALOG2 */
#define XBOX2            91  /* IBOX in Baum DIALOG2 */
#define XWAIT            92  /* BUTTON in Baum DIALOG2 */
#define XNOMAIL          93  /* BUTTON in Baum DIALOG2 */
#define XAUTOPOL         94  /* BUTTON in Baum DIALOG2 */
#define XLOOP            95  /* BUTTON in Baum DIALOG2 */
#define XLOOPCNT         96  /* FTEXT in Baum DIALOG2 */
#define XSELECT          97  /* BUTTON in Baum DIALOG2 */
#define XDELONE          98  /* BOXTEXT in Baum DIALOG2 */
#define XDELALL          99  /* BOXTEXT in Baum DIALOG2 */
#define TIMEONE          102 /* FTEXT in Baum DIALOG2 */
#define TIMETWO          104 /* FTEXT in Baum DIALOG2 */
#define XOK              105 /* BUTTON in Baum DIALOG2 */

#define DIALOG3          2   /* Formular/Dialog */
#define AIMPORT          3   /* FTEXT in Baum DIALOG3 */
#define CIMPORT          4   /* BOX in Baum DIALOG3 */
#define AOK              5   /* BUTTON in Baum DIALOG3 */
#define BIMPORT          6   /* FTEXT in Baum DIALOG3 */
#define AEXPORT          7   /* FTEXT in Baum DIALOG3 */
#define CEXPORT          8   /* BOX in Baum DIALOG3 */
#define BEXPORT          9   /* FTEXT in Baum DIALOG3 */
#define ACRUNCH          10  /* FTEXT in Baum DIALOG3 */
#define CCRUNCH          11  /* BOX in Baum DIALOG3 */
#define BCRUNCH          12  /* FTEXT in Baum DIALOG3 */
#define ASCANNER         13  /* FTEXT in Baum DIALOG3 */
#define CSCANNER         14  /* BOX in Baum DIALOG3 */
#define BSCANNER         15  /* FTEXT in Baum DIALOG3 */
#define AMSGED           16  /* FTEXT in Baum DIALOG3 */
#define CMSGED           17  /* BOX in Baum DIALOG3 */
#define BMSGED           18  /* FTEXT in Baum DIALOG3 */
#define ATXTED           19  /* FTEXT in Baum DIALOG3 */
#define CTXTED           20  /* BOX in Baum DIALOG3 */
#define BTXTED           21  /* FTEXT in Baum DIALOG3 */
#define AMAILER          22  /* FTEXT in Baum DIALOG3 */
#define CMAILER          23  /* BOX in Baum DIALOG3 */
#define BMAILER          24  /* FTEXT in Baum DIALOG3 */
#define ATERM            25  /* FTEXT in Baum DIALOG3 */
#define CTERM            26  /* BOX in Baum DIALOG3 */
#define BTERM            27  /* FTEXT in Baum DIALOG3 */
#define ANOTICE          28  /* TEXT in Baum DIALOG3 */
#define AVIEW            29  /* FTEXT in Baum DIALOG3 */
#define ACANCEL          30  /* BOXTEXT in Baum DIALOG3 */
#define ABBSTEXT         31  /* STRING in Baum DIALOG3 */
#define ABBSEDIT         32  /* FTEXT in Baum DIALOG3 */

#define DIALOG5          3   /* Formular/Dialog */
#define XCMD             1   /* FTEXT in Baum DIALOG5 */
#define XCMDOK           2   /* BUTTON in Baum DIALOG5 */

#define DIALOG6          4   /* Formular/Dialog */
#define XPOLLTIM         1   /* FBOXTEXT in Baum DIALOG6 */
#define XPOLLCAN         2   /* BUTTON in Baum DIALOG6 */
#define XPOLLOK          3   /* BUTTON in Baum DIALOG6 */

#define DIALOG7          5   /* Formular/Dialog */
#define ORIGIN0          2   /* FTEXT in Baum DIALOG7 */
#define BOSS0            3   /* FTEXT in Baum DIALOG7 */
#define CNTAREAS         4   /* FTEXT in Baum DIALOG7 */
#define CNTMAX           5   /* FTEXT in Baum DIALOG7 */
#define AREASBOX         8   /* IBOX in Baum DIALOG7 */
#define DNAME1           10  /* FTEXT in Baum DIALOG7 */
#define DAYS1            11  /* FTEXT in Baum DIALOG7 */
#define BOSS1            12  /* FTEXT in Baum DIALOG7 */
#define NPATH1           13  /* STRING in Baum DIALOG7 */
#define PATH1            14  /* FTEXT in Baum DIALOG7 */
#define NORG1            15  /* STRING in Baum DIALOG7 */
#define ORIGIN1          16  /* FTEXT in Baum DIALOG7 */
#define DNAME2           18  /* FTEXT in Baum DIALOG7 */
#define DAYS2            19  /* FTEXT in Baum DIALOG7 */
#define BOSS2            20  /* FTEXT in Baum DIALOG7 */
#define NPATH2           21  /* STRING in Baum DIALOG7 */
#define PATH2            22  /* FTEXT in Baum DIALOG7 */
#define NORG2            23  /* STRING in Baum DIALOG7 */
#define ORIGIN2          24  /* FTEXT in Baum DIALOG7 */
#define DNAME3           26  /* FTEXT in Baum DIALOG7 */
#define DAYS3            27  /* FTEXT in Baum DIALOG7 */
#define BOSS3            28  /* FTEXT in Baum DIALOG7 */
#define NPATH3           29  /* STRING in Baum DIALOG7 */
#define PATH3            30  /* FTEXT in Baum DIALOG7 */
#define NORG3            31  /* STRING in Baum DIALOG7 */
#define ORIGIN3          32  /* FTEXT in Baum DIALOG7 */
#define NODE1            33  /* BOXTEXT in Baum DIALOG7 */
#define EXTEND1          34  /* BOXTEXT in Baum DIALOG7 */
#define INSERT1          35  /* BOXTEXT in Baum DIALOG7 */
#define DELETE1          36  /* BOXTEXT in Baum DIALOG7 */
#define NODE2            38  /* BOXTEXT in Baum DIALOG7 */
#define EXTEND2          39  /* BOXTEXT in Baum DIALOG7 */
#define INSERT2          40  /* BOXTEXT in Baum DIALOG7 */
#define DELETE2          41  /* BOXTEXT in Baum DIALOG7 */
#define NODE3            43  /* BOXTEXT in Baum DIALOG7 */
#define EXTEND3          44  /* BOXTEXT in Baum DIALOG7 */
#define INSERT3          45  /* BOXTEXT in Baum DIALOG7 */
#define DELETE3          46  /* BOXTEXT in Baum DIALOG7 */
#define ARROWFUL         47  /* IBOX in Baum DIALOG7 */
#define ARROWDN          48  /* BOXCHAR in Baum DIALOG7 */
#define ARROWBK          49  /* BOX in Baum DIALOG7 */
#define ARROWFD          50  /* BOX in Baum DIALOG7 */
#define ARROWUP          51  /* BOXCHAR in Baum DIALOG7 */
#define ARSEARCH         52  /* BUTTON in Baum DIALOG7 */
#define ARINSERT         53  /* BOXTEXT in Baum DIALOG7 */
#define ARCANCEL         54  /* BUTTON in Baum DIALOG7 */
#define AROK             55  /* BUTTON in Baum DIALOG7 */

#define DIALOG8          6   /* Formular/Dialog */
#define REQNODE          2   /* FBOXTEXT in Baum DIALOG8 */
#define REQLEFT          5   /* IBOX in Baum DIALOG8 */
#define PROG1            6   /* FTEXT in Baum DIALOG8 */
#define PASS1            7   /* FTEXT in Baum DIALOG8 */
#define PROG2            8   /* FTEXT in Baum DIALOG8 */
#define PASS2            9   /* FTEXT in Baum DIALOG8 */
#define PROG3            10  /* FTEXT in Baum DIALOG8 */
#define PASS3            11  /* FTEXT in Baum DIALOG8 */
#define PROG4            12  /* FTEXT in Baum DIALOG8 */
#define PASS4            13  /* FTEXT in Baum DIALOG8 */
#define PROG5            14  /* FTEXT in Baum DIALOG8 */
#define PASS5            15  /* FTEXT in Baum DIALOG8 */
#define PROG6            16  /* FTEXT in Baum DIALOG8 */
#define PASS6            17  /* FTEXT in Baum DIALOG8 */
#define PROG7            18  /* FTEXT in Baum DIALOG8 */
#define PASS7            19  /* FTEXT in Baum DIALOG8 */
#define PROG8            20  /* FTEXT in Baum DIALOG8 */
#define PASS8            21  /* FTEXT in Baum DIALOG8 */
#define PROG9            22  /* FTEXT in Baum DIALOG8 */
#define PASS9            23  /* FTEXT in Baum DIALOG8 */
#define PROG10           24  /* FTEXT in Baum DIALOG8 */
#define PASS10           25  /* FTEXT in Baum DIALOG8 */
#define REQRIGHT         26  /* IBOX in Baum DIALOG8 */
#define PROG11           27  /* FTEXT in Baum DIALOG8 */
#define PASS11           28  /* FTEXT in Baum DIALOG8 */
#define PROG12           29  /* FTEXT in Baum DIALOG8 */
#define PASS12           30  /* FTEXT in Baum DIALOG8 */
#define PROG13           31  /* FTEXT in Baum DIALOG8 */
#define PASS13           32  /* FTEXT in Baum DIALOG8 */
#define PROG14           33  /* FTEXT in Baum DIALOG8 */
#define PASS14           34  /* FTEXT in Baum DIALOG8 */
#define PROG15           35  /* FTEXT in Baum DIALOG8 */
#define PASS15           36  /* FTEXT in Baum DIALOG8 */
#define PROG16           37  /* FTEXT in Baum DIALOG8 */
#define PASS16           38  /* FTEXT in Baum DIALOG8 */
#define PROG17           39  /* FTEXT in Baum DIALOG8 */
#define PASS17           40  /* FTEXT in Baum DIALOG8 */
#define PROG18           41  /* FTEXT in Baum DIALOG8 */
#define PASS18           42  /* FTEXT in Baum DIALOG8 */
#define PROG19           43  /* FTEXT in Baum DIALOG8 */
#define PASS19           44  /* FTEXT in Baum DIALOG8 */
#define PROG20           45  /* FTEXT in Baum DIALOG8 */
#define PASS20           46  /* FTEXT in Baum DIALOG8 */
#define REQBOXES         47  /* BOX in Baum DIALOG8 */
#define GETNODE1         48  /* BOXTEXT in Baum DIALOG8 */
#define GETNODE2         49  /* BOXTEXT in Baum DIALOG8 */
#define GETNODE3         50  /* BOXTEXT in Baum DIALOG8 */
#define GETNODE4         51  /* BOXTEXT in Baum DIALOG8 */
#define GETNODE5         52  /* BOXTEXT in Baum DIALOG8 */
#define GETNODE6         53  /* BOXTEXT in Baum DIALOG8 */
#define GETNODE7         54  /* BOXTEXT in Baum DIALOG8 */
#define GETNODE8         55  /* BOXTEXT in Baum DIALOG8 */
#define GETNODE9         56  /* BOXTEXT in Baum DIALOG8 */
#define GETNODE0         57  /* BOXTEXT in Baum DIALOG8 */
#define REQBOX2          58  /* BOX in Baum DIALOG8 */
#define FILELST0         59  /* BOXTEXT in Baum DIALOG8 */
#define FILELST1         60  /* BOXTEXT in Baum DIALOG8 */
#define FILELST2         61  /* BOXTEXT in Baum DIALOG8 */
#define FILELST3         62  /* BOXTEXT in Baum DIALOG8 */
#define FILELST4         63  /* BOXTEXT in Baum DIALOG8 */
#define FILELST5         64  /* BOXTEXT in Baum DIALOG8 */
#define FILELST6         65  /* BOXTEXT in Baum DIALOG8 */
#define FILELST7         66  /* BOXTEXT in Baum DIALOG8 */
#define FILELST8         67  /* BOXTEXT in Baum DIALOG8 */
#define FILELST9         68  /* BOXTEXT in Baum DIALOG8 */
#define REQDEF           75  /* BOX in Baum DIALOG8 */
#define GETFILE1         76  /* FTEXT in Baum DIALOG8 */
#define GETFILE2         77  /* FTEXT in Baum DIALOG8 */
#define GETFILE3         78  /* FTEXT in Baum DIALOG8 */
#define GETFILE4         79  /* FTEXT in Baum DIALOG8 */
#define REQLOAD          81  /* BOXTEXT in Baum DIALOG8 */
#define REQSELEC         82  /* BOXTEXT in Baum DIALOG8 */
#define REQFILES         83  /* BOXTEXT in Baum DIALOG8 */
#define REQCLEAR         84  /* BOXTEXT in Baum DIALOG8 */
#define REQBLOCK         85  /* BOXTEXT in Baum DIALOG8 */
#define REQSAVEZ         86  /* BUTTON in Baum DIALOG8 */
#define REQSAVE          87  /* BUTTON in Baum DIALOG8 */
#define REQCANCE         88  /* BUTTON in Baum DIALOG8 */

#define DIALOG9          7   /* Formular/Dialog */
#define FBOX             1   /* BOX in Baum DIALOG9 */
#define FNAME1           2   /* STRING in Baum DIALOG9 */
#define FNAME2           3   /* STRING in Baum DIALOG9 */
#define FNAME3           4   /* STRING in Baum DIALOG9 */
#define FNAME4           5   /* STRING in Baum DIALOG9 */
#define FNAME5           6   /* STRING in Baum DIALOG9 */
#define FNAME6           7   /* STRING in Baum DIALOG9 */
#define FNAME7           8   /* STRING in Baum DIALOG9 */
#define FNAME8           9   /* STRING in Baum DIALOG9 */
#define FNAME9           10  /* STRING in Baum DIALOG9 */
#define FNAME10          11  /* STRING in Baum DIALOG9 */
#define FNAME11          12  /* STRING in Baum DIALOG9 */
#define FNAME12          13  /* STRING in Baum DIALOG9 */
#define FNAME13          14  /* STRING in Baum DIALOG9 */
#define FNAME14          15  /* STRING in Baum DIALOG9 */
#define FNAME15          16  /* STRING in Baum DIALOG9 */
#define FNAME16          17  /* STRING in Baum DIALOG9 */
#define FNAME17          18  /* STRING in Baum DIALOG9 */
#define FNAME18          19  /* STRING in Baum DIALOG9 */
#define FILEFULL         20  /* IBOX in Baum DIALOG9 */
#define FILEDNDN         21  /* BOXTEXT in Baum DIALOG9 */
#define FILEDN           22  /* BOXCHAR in Baum DIALOG9 */
#define FILEBK           23  /* BOX in Baum DIALOG9 */
#define FILEFD           24  /* BOX in Baum DIALOG9 */
#define FILEUP           25  /* BOXCHAR in Baum DIALOG9 */
#define FILEUPUP         26  /* BOXTEXT in Baum DIALOG9 */
#define FOK              27  /* BUTTON in Baum DIALOG9 */
#define REQINFO          28  /* TEXT in Baum DIALOG9 */

#define DIALOG10         8   /* Formular/Dialog */
#define PASSEDIT         1   /* FBOXTEXT in Baum DIALOG10 */
#define PASSOK           2   /* BUTTON in Baum DIALOG10 */

#define DIALOG11         9   /* Formular/Dialog */
#define INFOEXIT         40  /* BOXTEXT in Baum DIALOG11 */

#define DIALOG12         10  /* Menuebaum */
#define MINFO            11  /* STRING in Baum DIALOG12 */
#define MPOLL1           20  /* STRING in Baum DIALOG12 */
#define MPOLL2           21  /* STRING in Baum DIALOG12 */
#define MPOLL3           22  /* STRING in Baum DIALOG12 */
#define MPOLL4           23  /* STRING in Baum DIALOG12 */
#define MPOLL5           24  /* STRING in Baum DIALOG12 */
#define MPOLL6           25  /* STRING in Baum DIALOG12 */
#define MAUTO1           27  /* STRING in Baum DIALOG12 */
#define MAUTO2           28  /* STRING in Baum DIALOG12 */
#define MAUTO3           29  /* STRING in Baum DIALOG12 */
#define MAUTO4           30  /* STRING in Baum DIALOG12 */
#define MAUTO5           31  /* STRING in Baum DIALOG12 */
#define MAUTO6           32  /* STRING in Baum DIALOG12 */
#define MRESTART         34  /* STRING in Baum DIALOG12 */
#define MQUIT            36  /* STRING in Baum DIALOG12 */
#define MIMPORT          38  /* STRING in Baum DIALOG12 */
#define MEXPORT          39  /* STRING in Baum DIALOG12 */
#define MCRUNCH          40  /* STRING in Baum DIALOG12 */
#define MSCANNER         41  /* STRING in Baum DIALOG12 */
#define MMAILER          43  /* STRING in Baum DIALOG12 */
#define MTERM            44  /* STRING in Baum DIALOG12 */
#define MMSGEDIT         46  /* STRING in Baum DIALOG12 */
#define MTXTEDIT         47  /* STRING in Baum DIALOG12 */
#define MAPP             49  /* STRING in Baum DIALOG12 */
#define MPRG             50  /* STRING in Baum DIALOG12 */
#define MTOS             51  /* STRING in Baum DIALOG12 */
#define MTTP             52  /* STRING in Baum DIALOG12 */
#define MALL             53  /* STRING in Baum DIALOG12 */
#define MSTAR            54  /* STRING in Baum DIALOG12 */
#define MUTIL1           56  /* STRING in Baum DIALOG12 */
#define MUTIL2           57  /* STRING in Baum DIALOG12 */
#define MUTIL3           58  /* STRING in Baum DIALOG12 */
#define MUTIL4           59  /* STRING in Baum DIALOG12 */
#define MUTIL5           60  /* STRING in Baum DIALOG12 */
#define MUTIL6           61  /* STRING in Baum DIALOG12 */
#define MFILEREQ         63  /* STRING in Baum DIALOG12 */
#define MHATCH           65  /* STRING in Baum DIALOG12 */
#define MFIX             67  /* STRING in Baum DIALOG12 */
#define MMANAGER         69  /* STRING in Baum DIALOG12 */
#define MFTERM           70  /* STRING in Baum DIALOG12 */
#define MPMANAGE         71  /* STRING in Baum DIALOG12 */
#define MNOTE            73  /* STRING in Baum DIALOG12 */
#define MSSETUP          75  /* STRING in Baum DIALOG12 */
#define MFINDPRG         76  /* STRING in Baum DIALOG12 */
#define MFINDUTL         77  /* STRING in Baum DIALOG12 */
#define MAREAS           78  /* STRING in Baum DIALOG12 */
#define MSPEZIAL         79  /* STRING in Baum DIALOG12 */
#define MPOINT1          81  /* STRING in Baum DIALOG12 */
#define MPOINT2          82  /* STRING in Baum DIALOG12 */
#define MPOINT3          83  /* STRING in Baum DIALOG12 */
#define MPOINT4          84  /* STRING in Baum DIALOG12 */
#define MPOINT5          85  /* STRING in Baum DIALOG12 */
#define MPOINT6          86  /* STRING in Baum DIALOG12 */
#define MREREAD          88  /* STRING in Baum DIALOG12 */
#define MSAVE            90  /* STRING in Baum DIALOG12 */

#define DIALOG13         11  /* Formular/Dialog */
#define PRESSKEY         1   /* BOXTEXT in Baum DIALOG13 */

#define DIALOG14         12  /* Formular/Dialog */
#define FINDTEXT         1   /* FTEXT in Baum DIALOG14 */
#define FINDABB          2   /* BUTTON in Baum DIALOG14 */
#define FINDOK           3   /* BUTTON in Baum DIALOG14 */

#define DIALOG15         13  /* Formular/Dialog */
#define PAREAS           3   /* FTEXT in Baum DIALOG15 */
#define PBINKLEY         4   /* FTEXT in Baum DIALOG15 */
#define PSEMPER          6   /* FTEXT in Baum DIALOG15 */
#define PNETMAIL         9   /* FTEXT in Baum DIALOG15 */
#define NAMSET1          12  /* FTEXT in Baum DIALOG15 */
#define NAMSET2          14  /* FTEXT in Baum DIALOG15 */
#define NAMSET3          16  /* FTEXT in Baum DIALOG15 */
#define NAMSET4          18  /* FTEXT in Baum DIALOG15 */
#define NAMSET5          20  /* FTEXT in Baum DIALOG15 */
#define NAMSET6          22  /* FTEXT in Baum DIALOG15 */
#define USE000           26  /* BUTTON in Baum DIALOG15 */
#define USE241           27  /* BUTTON in Baum DIALOG15 */
#define USE999           28  /* BUTTON in Baum DIALOG15 */
#define KSHATCH          31  /* BUTTON in Baum DIALOG15 */
#define KSFIX            32  /* BUTTON in Baum DIALOG15 */
#define USEDSIZE         33  /* FTEXT in Baum DIALOG15 */
#define CHECKON          34  /* BOX in Baum DIALOG15 */
#define USEMAXI          36  /* BOX in Baum DIALOG15 */
#define KEYPON           38  /* BOX in Baum DIALOG15 */
#define USECENTR         40  /* BOX in Baum DIALOG15 */
#define REDIRECT         42  /* BOX in Baum DIALOG15 */
#define USESNAP          44  /* BOX in Baum DIALOG15 */
#define USE4DON          46  /* BOX in Baum DIALOG15 */
#define USENOLNA         48  /* BOX in Baum DIALOG15 */
#define USEDELAY         50  /* BOX in Baum DIALOG15 */
#define USESMART         52  /* BOX in Baum DIALOG15 */
#define USEDBBS          54  /* BOX in Baum DIALOG15 */
#define BOXON            56  /* BOX in Baum DIALOG15 */
#define BOXSMALL         58  /* BOX in Baum DIALOG15 */
#define SAVEON           60  /* BOX in Baum DIALOG15 */
#define USEBUFF          62  /* BOX in Baum DIALOG15 */
#define USE3DON          64  /* BOX in Baum DIALOG15 */
#define USEOUT36         66  /* BOX in Baum DIALOG15 */
#define POK              68  /* BUTTON in Baum DIALOG15 */

#define DIALOG16         14  /* Formular/Dialog */
#define MANSHIP          2   /* BOXTEXT in Baum DIALOG16 */
#define MANTERM          3   /* BOXTEXT in Baum DIALOG16 */
#define MANSYS           5   /* BOXTEXT in Baum DIALOG16 */
#define MANOUT           6   /* BOXTEXT in Baum DIALOG16 */
#define MANMSGS          7   /* BOXTEXT in Baum DIALOG16 */
#define MANREF           8   /* BOXTEXT in Baum DIALOG16 */
#define MANCOPY          9   /* BOXTEXT in Baum DIALOG16 */
#define MANMOVE          10  /* BOXTEXT in Baum DIALOG16 */
#define MANDEL           11  /* BOXTEXT in Baum DIALOG16 */
#define MANREN           12  /* BOXTEXT in Baum DIALOG16 */
#define MANINFO          13  /* BOXTEXT in Baum DIALOG16 */
#define MANVIEW          14  /* BOXTEXT in Baum DIALOG16 */

#define DIALOG17         15  /* Formular/Dialog */
#define IMANAG1          1   /* STRING in Baum DIALOG17 */
#define IMANAG2          2   /* STRING in Baum DIALOG17 */

#define DIALOG18         16  /* Formular/Dialog */
#define NOTEBOX          2   /* BOX in Baum DIALOG18 */
#define NOTE1            3   /* FTEXT in Baum DIALOG18 */
#define NOTE2            4   /* FTEXT in Baum DIALOG18 */
#define NOTE3            5   /* FTEXT in Baum DIALOG18 */
#define NOTE4            6   /* FTEXT in Baum DIALOG18 */
#define NOTE5            7   /* FTEXT in Baum DIALOG18 */
#define NOTE6            8   /* FTEXT in Baum DIALOG18 */
#define NOTE7            9   /* FTEXT in Baum DIALOG18 */
#define NOTE8            10  /* FTEXT in Baum DIALOG18 */
#define NOTE9            11  /* FTEXT in Baum DIALOG18 */
#define NOTEA            12  /* FTEXT in Baum DIALOG18 */
#define NOTEB            13  /* FTEXT in Baum DIALOG18 */
#define NOTEC            14  /* FTEXT in Baum DIALOG18 */
#define NOTECLR          15  /* BUTTON in Baum DIALOG18 */
#define NOTELOAD         16  /* BUTTON in Baum DIALOG18 */
#define NOTEFF           17  /* BUTTON in Baum DIALOG18 */
#define NOTEPRN          18  /* BUTTON in Baum DIALOG18 */
#define NOTECANC         19  /* BUTTON in Baum DIALOG18 */
#define NOTEEXIT         20  /* BUTTON in Baum DIALOG18 */

#define DIALOG71         17  /* Formular/Dialog */
#define AREAS1           67  /* FTEXT in Baum DIALOG71 */
#define AREAS2           68  /* FTEXT in Baum DIALOG71 */
#define AREAS3           69  /* FTEXT in Baum DIALOG71 */
#define AREAS4           70  /* FTEXT in Baum DIALOG71 */
#define AREAS5           71  /* FTEXT in Baum DIALOG71 */
#define AREAS6           72  /* FTEXT in Baum DIALOG71 */
#define AREAS7           73  /* FTEXT in Baum DIALOG71 */
#define AREAS8           74  /* FTEXT in Baum DIALOG71 */
#define EXTENDOK         75  /* BUTTON in Baum DIALOG71 */

#define DIALOG81         18  /* Formular/Dialog */
#define REQZONE          2   /* FTEXT in Baum DIALOG81 */
#define REQDOMAI         3   /* FTEXT in Baum DIALOG81 */
#define PRESET0          6   /* BOXTEXT in Baum DIALOG81 */
#define PRESET1          7   /* BOXTEXT in Baum DIALOG81 */
#define PRESET2          8   /* BOXTEXT in Baum DIALOG81 */
#define PRESET3          9   /* BOXTEXT in Baum DIALOG81 */
#define PRESET4          10  /* BOXTEXT in Baum DIALOG81 */
#define PRESET5          11  /* BOXTEXT in Baum DIALOG81 */
#define PRESET6          12  /* BOXTEXT in Baum DIALOG81 */
#define PRESET7          13  /* BOXTEXT in Baum DIALOG81 */
#define REQZCAN          14  /* BUTTON in Baum DIALOG81 */
#define REQZSAVE         15  /* BUTTON in Baum DIALOG81 */

#define DIALOG31         19  /* Formular/Dialog */
#define DUTIL1           3   /* FTEXT in Baum DIALOG31 */
#define BOK              4   /* BUTTON in Baum DIALOG31 */
#define AUTIL1           5   /* FTEXT in Baum DIALOG31 */
#define CUTIL1           6   /* BOX in Baum DIALOG31 */
#define BUTIL1           7   /* FTEXT in Baum DIALOG31 */
#define DUTIL2           8   /* FTEXT in Baum DIALOG31 */
#define AUTIL2           9   /* FTEXT in Baum DIALOG31 */
#define CUTIL2           10  /* BOX in Baum DIALOG31 */
#define BUTIL2           11  /* FTEXT in Baum DIALOG31 */
#define DUTIL3           12  /* FTEXT in Baum DIALOG31 */
#define AUTIL3           13  /* FTEXT in Baum DIALOG31 */
#define CUTIL3           14  /* BOX in Baum DIALOG31 */
#define BUTIL3           15  /* FTEXT in Baum DIALOG31 */
#define DUTIL4           16  /* FTEXT in Baum DIALOG31 */
#define AUTIL4           17  /* FTEXT in Baum DIALOG31 */
#define CUTIL4           18  /* BOX in Baum DIALOG31 */
#define BUTIL4           19  /* FTEXT in Baum DIALOG31 */
#define DUTIL5           20  /* FTEXT in Baum DIALOG31 */
#define AUTIL5           21  /* FTEXT in Baum DIALOG31 */
#define CUTIL5           22  /* BOX in Baum DIALOG31 */
#define BUTIL5           23  /* FTEXT in Baum DIALOG31 */
#define DUTIL6           24  /* FTEXT in Baum DIALOG31 */
#define AUTIL6           25  /* FTEXT in Baum DIALOG31 */
#define CUTIL6           26  /* BOX in Baum DIALOG31 */
#define BCANCEL          27  /* BOXTEXT in Baum DIALOG31 */
#define BUTIL6           28  /* FTEXT in Baum DIALOG31 */

#define DIALOG72         20  /* Formular/Dialog */
#define XAREA            3   /* STRING in Baum DIALOG72 */
#define XNODE            5   /* STRING in Baum DIALOG72 */
#define NLINE1           7   /* FTEXT in Baum DIALOG72 */
#define NLINE2           8   /* FTEXT in Baum DIALOG72 */
#define NLINE3           9   /* FTEXT in Baum DIALOG72 */

#define DIALOG21         21  /* Formular/Dialog */
#define SESSTEXT         1   /* FBOXTEXT in Baum DIALOG21 */

#define DIALOG82         22  /* Formular/Dialog */
#define FILETEXT         1   /* FTEXT in Baum DIALOG82 */
#define FILENODE         2   /* FTEXT in Baum DIALOG82 */
#define FILEPATH         4   /* FTEXT in Baum DIALOG82 */
#define FILEOK           9   /* BUTTON in Baum DIALOG82 */

#define DIALOG19         23  /* Formular/Dialog */
#define TIMEBOXT         1   /* TEXT in Baum DIALOG19 */
#define MAXTIME          2   /* BOX in Baum DIALOG19 */
#define LEFTTIME         3   /* BOX in Baum DIALOG19 */
#define TIMEBOXS         4   /* TEXT in Baum DIALOG19 */

#define DIALOG61         24  /* Formular/Dialog */
#define APOLLTIM         1   /* FBOXTEXT in Baum DIALOG61 */
#define ATIME            3   /* FBOXTEXT in Baum DIALOG61 */

#define DIALOG20         25  /* Formular/Dialog */
#define DUMMYPIC         1   /* IMAGE in Baum DIALOG20 */

#define DIALOG51         26  /* Formular/Dialog */
#define XCMD1            1   /* FTEXT in Baum DIALOG51 */
#define XCMDDEL          3   /* BUTTON in Baum DIALOG51 */
#define XCMDINS          6   /* BUTTON in Baum DIALOG51 */
#define XCMDOK1          8   /* BUTTON in Baum DIALOG51 */
#define XCMDGL1          9   /* BUTTON in Baum DIALOG51 */
#define XCMDCA1          10  /* BUTTON in Baum DIALOG51 */

#define DIALOG22         27  /* Formular/Dialog */
#define SENDFILE         4   /* FTEXT in Baum DIALOG22 */
#define SENDFLAG         6   /* IBOX in Baum DIALOG22 */
#define SENDNORM         7   /* BOXTEXT in Baum DIALOG22 */
#define SENDCRAS         8   /* BOXTEXT in Baum DIALOG22 */
#define SENDHOLD         9   /* BOXTEXT in Baum DIALOG22 */
#define SENDDIRE         10  /* BOXTEXT in Baum DIALOG22 */
#define SENDTOUC         11  /* BOXTEXT in Baum DIALOG22 */
#define SENDNODE         12  /* FTEXT in Baum DIALOG22 */
#define SENDTXT1         14  /* FTEXT in Baum DIALOG22 */
#define SENDTXT2         15  /* FTEXT in Baum DIALOG22 */
#define SENDTXT3         16  /* FTEXT in Baum DIALOG22 */
#define SENDAREA         17  /* FTEXT in Baum DIALOG22 */
#define SENDPASS         18  /* FTEXT in Baum DIALOG22 */
#define SENDREPL         19  /* FTEXT in Baum DIALOG22 */
#define SENDMAIL         23  /* BOXTEXT in Baum DIALOG22 */
#define SENDREP1         24  /* BOXTEXT in Baum DIALOG22 */
#define SENDREP2         25  /* BOXTEXT in Baum DIALOG22 */
#define SENDNAME         26  /* FTEXT in Baum DIALOG22 */
#define SENDDEF1         29  /* BOXTEXT in Baum DIALOG22 */
#define SENDDEF2         30  /* BOXTEXT in Baum DIALOG22 */
#define SENDDEF3         31  /* BOXTEXT in Baum DIALOG22 */
#define SENDDEF4         32  /* BOXTEXT in Baum DIALOG22 */
#define SENDDEF5         33  /* BOXTEXT in Baum DIALOG22 */
#define SENDDEF6         34  /* BOXTEXT in Baum DIALOG22 */
#define SENDDEF7         35  /* BOXTEXT in Baum DIALOG22 */
#define SENDDEF8         36  /* BOXTEXT in Baum DIALOG22 */
#define SENDDEF9         37  /* BOXTEXT in Baum DIALOG22 */
#define SENDSAVZ         38  /* BUTTON in Baum DIALOG22 */
#define SENDSAVE         39  /* BUTTON in Baum DIALOG22 */
#define SENDCANC         40  /* BUTTON in Baum DIALOG22 */
#define SENDNONE         43  /* BOXTEXT in Baum DIALOG22 */
#define SENDTIC          44  /* BOXTEXT in Baum DIALOG22 */
#define SENDATTA         45  /* BOXTEXT in Baum DIALOG22 */
#define SENDLOAD         46  /* BUTTON in Baum DIALOG22 */

#define DIALOG23         28  /* Formular/Dialog */
#define DEFNAME          1   /* FTEXT in Baum DIALOG23 */
#define DEFNODE          2   /* FTEXT in Baum DIALOG23 */
#define DEFSYSOP         3   /* FTEXT in Baum DIALOG23 */
#define DEFAREA          4   /* FTEXT in Baum DIALOG23 */
#define DEFPASS          5   /* FTEXT in Baum DIALOG23 */
#define DEFOK            6   /* BUTTON in Baum DIALOG23 */

#define DIALOG24         29  /* Formular/Dialog */
#define EDITTEXT         1   /* FBOXTEXT in Baum DIALOG24 */
#define EDITMAIL         2   /* FTEXT in Baum DIALOG24 */
#define EDITNAME         4   /* FTEXT in Baum DIALOG24 */
#define EDITOK           5   /* BUTTON in Baum DIALOG24 */

#define DIALOG52         30  /* Formular/Dialog */
#define XCMD2            1   /* FTEXT in Baum DIALOG52 */
#define XCMDDEL2         3   /* BUTTON in Baum DIALOG52 */
#define XCMDINS2         6   /* BUTTON in Baum DIALOG52 */
#define XCMDOK2          7   /* BUTTON in Baum DIALOG52 */

#define DIALOG25         31  /* Formular/Dialog */
#define FIXBOX           2   /* BOX in Baum DIALOG25 */
#define FIX1             3   /* STRING in Baum DIALOG25 */
#define FIX2             4   /* STRING in Baum DIALOG25 */
#define FIX3             5   /* STRING in Baum DIALOG25 */
#define FIX4             6   /* STRING in Baum DIALOG25 */
#define FIX5             7   /* STRING in Baum DIALOG25 */
#define FIX6             8   /* STRING in Baum DIALOG25 */
#define FIX7             9   /* STRING in Baum DIALOG25 */
#define FIX8             10  /* STRING in Baum DIALOG25 */
#define FIX9             11  /* STRING in Baum DIALOG25 */
#define FIX10            12  /* STRING in Baum DIALOG25 */
#define FIXMAX           13  /* FTEXT in Baum DIALOG25 */
#define FIXFULL          14  /* IBOX in Baum DIALOG25 */
#define FIXUPUP          15  /* BOXTEXT in Baum DIALOG25 */
#define FIXUP            16  /* BOXCHAR in Baum DIALOG25 */
#define FIXBK            17  /* BOX in Baum DIALOG25 */
#define FIXFD            18  /* BOX in Baum DIALOG25 */
#define FIXDOWN          19  /* BOXCHAR in Baum DIALOG25 */
#define FIXDNDN          20  /* BOXTEXT in Baum DIALOG25 */
#define FIXCANC          22  /* BUTTON in Baum DIALOG25 */
#define FIXAREA          23  /* BUTTON in Baum DIALOG25 */

#define DIALOG26         32  /* Formular/Dialog */
#define PASSNODE         2   /* TEXT in Baum DIALOG26 */
#define FIXNAME          4   /* FTEXT in Baum DIALOG26 */
#define PASSDOMA         5   /* TEXT in Baum DIALOG26 */
#define PASSSUBJ         6   /* FTEXT in Baum DIALOG26 */
#define FIXNEXT          8   /* BUTTON in Baum DIALOG26 */
#define FIXOK            9   /* BUTTON in Baum DIALOG26 */

#define DIALOG27         33  /* Formular/Dialog */
#define AUTOAREA         1   /* BOXTEXT in Baum DIALOG27 */
#define AUTOBOSS         3   /* FTEXT in Baum DIALOG27 */
#define AUTOZONE         4   /* FTEXT in Baum DIALOG27 */
#define AUTODAYS         5   /* FTEXT in Baum DIALOG27 */
#define AUTOPATH         7   /* FTEXT in Baum DIALOG27 */
#define AUTOORG          9   /* FTEXT in Baum DIALOG27 */
#define AUTOCANC         10  /* BUTTON in Baum DIALOG27 */
#define AUTOOK           11  /* BUTTON in Baum DIALOG27 */

#define DIALOG28         34  /* Formular/Dialog */
#define HELPLST          1   /* STRING in Baum DIALOG28 */
#define HELPFIX          2   /* STRING in Baum DIALOG28 */
#define HELPREQ          15  /* STRING in Baum DIALOG28 */
#define HELPSND          16  /* STRING in Baum DIALOG28 */

#define DIALOG9B         35  /* Formular/Dialog */

#define DIALO25B         36  /* Formular/Dialog */

#define DIALOG29         37  /* Formular/Dialog */
#define MSGEDIT          1   /* FTEXT in Baum DIALOG29 */
#define MSGOK            2   /* BUTTON in Baum DIALOG29 */

#define DIALOG30         38  /* Formular/Dialog */
#define CSPECIAL         2   /* STRING in Baum DIALOG30 */
#define CFILELIS         3   /* STRING in Baum DIALOG30 */
#define CSESSION         4   /* STRING in Baum DIALOG30 */
#define CHATCHMA         5   /* STRING in Baum DIALOG30 */
#define CPROGRAM         6   /* STRING in Baum DIALOG30 */
#define CHATCHDE         7   /* STRING in Baum DIALOG30 */
#define CUTILITY         8   /* STRING in Baum DIALOG30 */
#define CTERMINA         9   /* STRING in Baum DIALOG30 */
#define CEPROGRA         10  /* STRING in Baum DIALOG30 */
#define DOCANCEL         11  /* BUTTON in Baum DIALOG30 */
#define AVALEXIT         12  /* BUTTON in Baum DIALOG30 */

#define DIALOG40         39  /* Formular/Dialog */
#define FIRSTSET         16  /* BUTTON in Baum DIALOG40 */

#define PICTURE0         40  /* Formular/Dialog */
#define AVALBLD0         1   /* IMAGE in Baum PICTURE0 */
#define AVALBLD1         2   /* IMAGE in Baum PICTURE0 */
#define ICFS0            3   /* IMAGE in Baum PICTURE0 */
#define ICFS1            4   /* IMAGE in Baum PICTURE0 */

#define DIALOG41         41  /* Formular/Dialog */
#define USESEMP          6   /* BUTTON in Baum DIALOG41 */
#define USEBINK          7   /* BUTTON in Baum DIALOG41 */

#define DIALOG33         42  /* Formular/Dialog */
#define EPROGREF         1   /* BOXTEXT in Baum DIALOG33 */
#define EPROG1           2   /* BOXTEXT in Baum DIALOG33 */
#define EPROG2           3   /* BOXTEXT in Baum DIALOG33 */
#define EPROG3           4   /* BOXTEXT in Baum DIALOG33 */
#define EPROG4           5   /* BOXTEXT in Baum DIALOG33 */
#define EPROG5           6   /* BOXTEXT in Baum DIALOG33 */
#define EPROG6           7   /* BOXTEXT in Baum DIALOG33 */
#define EPROG7           8   /* BOXTEXT in Baum DIALOG33 */
#define EPROG8           9   /* BOXTEXT in Baum DIALOG33 */
#define EPROG9           10  /* BOXTEXT in Baum DIALOG33 */
#define EPROG10          11  /* BOXTEXT in Baum DIALOG33 */
#define EPROG11          12  /* BOXTEXT in Baum DIALOG33 */
#define EPROG12          13  /* BOXTEXT in Baum DIALOG33 */
#define EPROG13          14  /* BOXTEXT in Baum DIALOG33 */
#define EPROG14          15  /* BOXTEXT in Baum DIALOG33 */
#define EPROG15          16  /* BOXTEXT in Baum DIALOG33 */

#define DIALOG34         43  /* Formular/Dialog */
#define ENAME            1   /* FTEXT in Baum DIALOG34 */
#define EREDIR           3   /* BOX in Baum DIALOG34 */
#define EPFAD            5   /* FTEXT in Baum DIALOG34 */
#define ECMD             7   /* FTEXT in Baum DIALOG34 */
#define EPROGOK          8   /* BUTTON in Baum DIALOG34 */

#define DIALOG90         44  /* Formular/Dialog */
#define INOHELP          4   /* BUTTON in Baum DIALOG90 */
#define INEEDHLP         5   /* BUTTON in Baum DIALOG90 */

#define DIALOG91         45  /* Formular/Dialog */
#define IOK              14  /* BUTTON in Baum DIALOG91 */

#define DIALOG99         46  /* Formular/Dialog */
#define ICFSPIC          1   /* IMAGE in Baum DIALOG99 */
