#include <stddef.h>

/* =============================================================== */
/* = Messages and templates AVALON =============================== */
/* =============================================================== */

char *msg[] = 
/*	0 */	{ "[3][ AES: appl_init failed |][ Exit ]",
						"[3][ Error in (D)AREAS.BBS! |][  OK  ]",
						NULL,		/* "[3][ You've made changes... | | Quit AVALON ?|][ Cancel |  Quit  ]", */
						"[3][ (D)AREAS.BBS not found! |][Check it]",
						NULL,		/* "[1][ AVALON does not run as accessory! |][ Sorry ]", */
/*	5 */		"[3][ Remember!| This program is| K E Y W A R E  !!! | Please register... ][ Thanx ]",
						"[3][ File not found! |][ Cancel ]",
						"[1][ Unknown or old config file! | Please check...|][ Cancel ]",
						"[1][ Please check filelengths! | There may be one file with | NULL-Bytes...|][  OK  ]",
						"[3][ BINKLEY.CFG not found! |][Check it]",
/* 10 */		"[1][ No program defined! |][Check it]",
						"[1][ Program not found |][Check it]",
						"[0][ No mail imported. | |][Continue|  Exit  ]",
						"[1][ No requestfile found for | this node!|][Cancel]",
						"[1][ No room for more files! |][  OK  ]",
/* 15 */		"[1][ Enter nodenumber correctly! |][  OK  ]",
						NULL,		/* "[0][ \1,\2 - Previous/Next page | \4,\3 - 10KB backwards/forwards |   F - Find string | G,N - Continue search | (Sh)Home - Start/End of list][  OK  ]", */
						"[3][ You reached the end of file! |][  OK  ]",
						"[3][ No search string defined! |][ Cancel ]",
						"[1][ Wrong or old KEY in | configuration file! | Please contact author...][Check it]",
/* 20 */		"[1][ Printer not ready! |][Check it]",
						"[1][ No session selected! |][ Abort ]",
						"[1][ No function yet! |][ Cancel ]",
						"[3][ AES: wind_create/delete failed |][ Exit ]",
						"[3][ Unregistered persons are not | allowed to use a beta version | of Avalon...|][ Sorry ]",
/* 25 */		"[1][ Program-Manager and | File-Manager only active | in main dialog!][  OK  ]",
						"[1][ Warning! | File and commandline cannot | be changed any more in | Find-1/2...][  OK  |Cancel]",
						"[3][ No domain defined in | BINKLEY.CFG! |][ Abort ]",
						"[3][ Domain not defined in | BINKLEY.CFG! |][ Abort ]",
						NULL,		/* "[0][ ALT: C)lear    L)oad |      F)iles    S)elect |      Z)oneReq  E)xit or Q)uit |      0)F'Select 1-9)Filelist |][  OK  ]", */
/* 30 */		"[3][ Netmail not defined! |][ Abort ]",
						"[1][ You used wildcards in the | 'replaces' field. | Is this OK...? |][ Cancel |   OK   ]",
						"[3][ Reportarea not defined! |][ Abort ]",
						"[3][ TOS: memory request failed |][ Exit ]",
						"[1][ Could not touch file! |][ Exit ]",
/* 35 */		"[1][ Please enter filearea! |][ Abort ]",
						"[3][ TOS: copybuffer in filecopy | not allocated... |][ Exit ]",
						"[2][ Edit AREAS.BBS or DAREAS.BBS? |][ AREAS | DAREAS ]",
						NULL,		/* "[0][ ALT: S)elect file  L)oad desc.|      Z)oneSend|      E)xit or Q)uit |][  OK  ]", */
						"[0][ \1,\2 - Line up/down  \4,\3 - Prev/Next msg| 1 click  - Select file | 2 clicks - Change address | Num block- Goto msg   ALT/Ctrl+Q - Exit ][  OK  ]",
/* 40 */		"[2][ Save options... |][Cancel|  OK  ]",
						"[3][ Out of memory... |][ Sorry ]",
						"[3][ Error in path/filename! | Please retype... |][  OK  ]",
						"[1][ Sorry! | No message stored in this | area... |][ Cancel ]",
						"[3][ ERROR! | Could not create AVALON folder! | Please check it... ][ Cancel ]",
/* 45 */		"[3][ File not found...|][ Sorry ]",
						"[2][ AVALON is already running...| Start again? |][  Yes  |   No   ]"
	};

char *tmsg[] =
/*  0 */	{ NULL,
						"[1][ No session defined!| Check Session-Setup %d |][Cancel]",
						"[1][ Programm terminates with | errorcode %ld |][  OK  |Cancel]",
						"[3][ To many entries in (D)AREAS.BBS! | Maximum is %u! |][  OK  ]",
						"[3][ Unable to open | %s | Write protected or | unknown path?][ Cancel ]",
/*	5 */		"[1][ BINKLEY.%u not found! |][Check it]",
						"[1][ New MsgBase: | %s |][ Cancel |Install]",
						"[1][ Delete old MsgBase: | %s |][ Cancel |   No   | Delete ]",
						"[3][ Unable to delete | %s | Write protected or | unknown path? ][ Cancel ]",
						"[2][ %u session(s) selected! |][ Cancel | Poll ]",
/* 10 */		"[0][ Happy birthday |      (%2d)|  dear Stephan][ Yeah! ]",
						"[3][ This is a beta release of| Avalon !| You use it on your own risk ! | Compiled %s, %s][  OK  ]",
						"[1][ I have found a undefined | program in Session-Setup %d. | Please check it! |][Cancel]",
						"[2][ Add | %s | to AREAS.BBS? |][  OK  | Cancel ]",
						"[2][ Add | %s | to (D)AREAS.BBS? |][ AREAS | DAREAS | Cancel ]",
/* 15 */		"[3][ To many entries in (D)AREAS.BBS | or AVALON.LST... | Maximum is %u! |][  OK  ]"
	};

/* =============================================================== */
/* = Strings AVALON ============================================== */
/* =============================================================== */

char	*avaltxt[] =
/*	0 */	{	"Please register!",
						"--- no node ---",
						"Select file",
						"Request-File",
						"Select filelist",
/*  5 */		"-------------- (D)AREAS.BBS and AVALON.LST not found. --------------", /* max.69 */
						"Select batch file",
						"Select other file",
						" not defined",	/* 12 chars */
						NULL,						/* "<no limit>", max.10 chars */
/* 10 */		"Execute batch",
						"Execute program",
						"Select file to send",
						"No origin for DAREAS.BBS",
						"Select file to show",
/* 15 */		"WARNING: This message has to many lines!"
					};

/* =============================================================== */
/* = Batchinterpreter ============================================ */
/* =============================================================== */

#if !defined( _AVALSEMP_ )

char *tbmsg[] = 
/*  0 */	{	"\33p!ERROR:\33q Execution errorcode: %ld",
						"\33p!ERROR:\33q Unable to kill %s",
						"\33p!ERROR:\33q Invalid drive %s",
						"Send to: %s (%s)",
						"\33p!ERROR:\33q Logfile not defined in Binkley.Cfg...",
/*  5 */		"\33p!ERROR:\33q TOS: copybuffer in filecopy not allocated...",
						"\n\033p Press any key... \033q\r",
						"\33p!ERROR:\33q Too many labels! Maximum is %d",
						"\33p!BREAK:\33q Really? (y to quit) ",
						"\33p!PAUSE:\33q Press any key (ESC to break) ",
/* 10 */		"\33p!BREAK:\33q Really? (y to quit)",
						"\33p!ERROR:\33q Filelength is zero in line %d",
						"\33p!ERROR:\33q Missing shell in line %d: >%s<",
						"\33p!ERROR:\33q Label not found %s",
						"\33p!ERROR:\33q Missing \'=<>#\' in line %u",
/* 15 */		"\33p!ERROR:\33q Unknown statement in line %d: >%s<",
						"\33p!ERROR:\33q TOS: memory allocation failed...",
						"\33p!ERROR:\33q Unable to open %s",
						"Printer not ready...",
						"\33p!ERROR:\33q CHDIR failed %s",
/* 20 */		"\33p!ERROR:\33q Unable to rename (move) %s %s",
						"\33p!ERROR:\33q DUMMYFILE failed %s",
						"\33p!ERROR:\33q Wrong parameter in line %d",
						"\33p!ERROR:\33q Missing source in line %d",
						"\33p!ERROR:\33q Missing destination in line %d",
/* 25 */		"\33p!ERROR:\33q Parameter out of range in line %d",
						"\33p!ERROR:\33q Calculation failed in line %d",
						"\33p!ERROR:\33q File already opened in line %d",
						"\33p!ERROR:\33q File open error in line %d",
						"\33p!ERROR:\33q File not open error in line %d",
/* 30 */		"\33p!ERROR:\33q SHIP: No XHDI 1.00 compatible HD driver installed in line %d",
						"\33p!ERROR:\33q Missing parameter in line %d",
						"\33p!ERROR:\33q Rename failed in line %d",
						"!REDIRECTION ignored in line %d (switch on 'Use window for...')",
						"\33p!ERROR:\33q File not found error in line %d",
/* 35 */		"!Today is %s",
						"!Copying NULL-length files is not very productive...",
						"!SWITCH to setup %d",
						"Monday",
						"Tuesday",
/* 40 */		"Wednesday",
						"Thursday",
						"Friday",
						"Saturday",
						"Sunday",
/* 45 */		"Append to file %s",
						"Open file %s",
						"File(s) not found",
						"!File exists. Skipping... %s",
						"Unable to open %s",
/* 50 */		"!Processing: %s to %s",
						"Directory of %s",
						" Waiting for %s h    (press any key to continue batch)",
						"Parking (%s %u/%u): %s",
						"\33p!ERROR:\33q !FILE or parameter missing in line %d",
/* 55 */		"\33p!ERROR:\33q !AREA or parameter missing in line %d",
						"\33p!ERROR:\33q !FROM or parameter missing in line %d",
						"\33p!ERROR:\33q !SEND parameter missing in line %d",
						"\33p!ERROR:\33q !SUBJECT or parameter missing in line %d",
						"\33p!ERROR:\33q !FLAGS or parameter missing in line %d",
/* 60 */		"\33p!ERROR:\33q Cannot recurse batchfiles in line %d"
	};

#endif

/* =============================================================== */
/* = Filemanager ================================================= */
/* =============================================================== */

#if !defined( _AVALSEMP_ )

char *mtmsg[] = 
/*  0 */	{	"File(s) not found: %s",
						"Unable to kill: %s",
						"Unable to open: %s",
						"Select source to copy",
						"Select source to move",
/*  5 */		"Select destination path",
						"File exists. Skipping... %s",
						"Processing: %s to %s",
						"Select file to delete",
						"Deleting: %s",
/* 10 */		"Select file to rename",
						"Enter new name (path to move)",
						"Rename: %s to %s",
						"Unable to rename: %s to %s",
						"Select file(s)",
/* 15 */		"View file",
						"Parking (%s %u/%u): %s",
						"Sorry! No XHDI 1.00 compatible HD driver installed.",
						"Opening logfile...",
						"Logfile cannot be opened twice...",
/* 20 */		"Closing logfile...",
						"Logfile???...",
						"Close logfile first...",
						"Full echo...",
						"Half echo...",
/* 25 */		"VT52 terminal...",
						"TTY terminal...",
						"Read Only",
						"Unable to open %s. Write protected or unknown path?",
						"GSZRZACC.ACC ???...",
/* 30	*/		"Sorry, wrong TOS version. Cannot change port...",
						"Port is: MFP (ST compatible, Modem-1)",
						"Port is: SCC-B (Modem-2)",
						"Port is: TTMFP (Seriell-1)",
						"Port is: SCC-A (Seriell-2)",
/* 35 */		"HELP:",
						"=====",
						" F1 - Open capturefile",
						" F2 - Close capturefile",
						" F3 - Delete capturefile",
/* 40 */		" F4 - Full/Half duplex",
						" F5 - VT100/VT52/TTY terminal",
						" F6 - Change serial port",
						" F7 - Send ZMODEM (GSZRZACC)",
						" F8 - Receive ZMODEM (GSZRZACC)",
/* 45 */		" F9 - Show file with emulation (TTY/VT52/VT100)",
						" F10- Send sysop's name",
						"DTE rate not supported (or unknown)...",
						"DTE rate: %u bps",
						"VT100 terminal...",
/* 50 */		"Deleting logfile...",
						"Logging is %s",
						"on",
						"off",
						"File not found: %s",
/* 55 */		"Wrap on...",
						"Wrap off...",
						"sF1 - Wrap on/off",
						"sF6 - Cycle baud rate",
						"",
/* 60 */		"",
						"",
						"",
						"",
						"",
/* 65 */		"",
						""
	};

#endif


char *registered[] =
	{
"=============================================================================",
"                         * * *   A V A L O N   * * *",
"=============================================================================",
"-",
"",
"Avalon, the greatest shell for fido points (and compatible networks).",
"",
"-",
"",
"You can ask me to generate a demokey if you want to test Avalon",
"a little bit longer. For more details: Please read the manual.",
"",
"-",
"",
"=============================================================================",
"",
"Thanks to following persons:",
"",
"Germany:",
"Erich Arning, Hans-Juergen Behnke, Arnd Bernstein, Christoph Bode,",
"Frank Bolinius, Hans-Dieter Brenner, Frank Brodmuehler, Peter Broll,",
"Helmut Buschmann, Justus Cohen, Dieter Daubenspeck, Florian Diete,",
"Roland Dieterich, Christof Drescher, Thomas Duchewitz, Peter Duemmler,",
"Torsten Edelmann, Frank Ellinghaus, Uwe Bernd Fahrbach, Jens Felderhoff,",
"Michael Fest, Oliver Foerster, Thomas Frasch, Siegfried Georgi,",
"Holger Giebeler, Thomas Grunwald, Michael Heidebuer, Michael Hesse,",
"Michael Hilgenstock, Andreas Hippe, Volker Horlitz, Michael Huebner,",
"Oliver Huf, Thomas Jox, Alfred Kaczmarek, Rolf Kaermer, Wolfgang Kaempf,",
"Max K”ppl, Horst Kollmuss, Robert Konietzny, Peter Kortulla, Bernd Kehren,",
"Christoph Kesselmeier, Peter Kotulla, Klaus Krall, Harald Krause,",
"Horst Krebs, Tim Kroeger, Christoph Lakenberg, Gerd Langenmeier,",
"Jochen Leufen, Christian van der Linde, Thomas Martin,",
"Berthold Menk, Markus Menne, Olaf Meyer, Matthias Neumann, Sven Over,",
"Gnther Paczia, Andreas Pietsch, Marco Pleuž, Karl-Heinz Protzer,",
"Adolf Rauch, Heinz Reinel, Klaus Reis, Philipp Reitberger, Uwe Reusche,",
"Beatrix Reusche, Arne Riewe, Daniel Roesen, Thorsten R”sicke,",
"Alexander Sauer, Helmut Schaaf, Joerg Schaefer, Uwe Peter Schiessl,",
"Dietmar Schmidt, Hermann Schmitt, Manfred Schmitt, Harald Schmitz,",
"Dietmar Selg, J”rg Spilker, J”rg Stadelhoff, Kurt Stalling,",
"Wolfgang Stichler, Markus Strasser, Matthias Stumm, Rolf Thieme,",
"Martin Vorl„nder, Thomas Wallutis, Thomas Weiž, Hartmut Wiechern,",
"Volkmar Wieners, Heiner Woestefeld, Prof.Dr.Peter Wunderli, Lars Zeyen",
"",
"Holland:",
"Robert Aerts, Rein Bakhuizen van den Brink, Robert Best, Harrie Beuvink,",
"Ted Camu, Godfried Cobben, Marijn de.Vries, Rob Deijkers, Max Dekker,",
"Tejo Duijn, George Faverey, Peter Habing, Erik Hajer, Ton Ketting,",
"Richard Kraaijkamp, Gerben Mondeel, Jan Polak, Emile Putting, Ruud Sint,",
"Hans Smits, Guus Spierings, Henri Spijkerman, Jan Harm ter Brugge,",
"Frits van der Veen, Nico Verkerk, Ronald van der Kamp, Joop van der Werff,",
"Will van Dongen, Toine van Rijthoven, Jan Schabbink, Eric van.Vloten,",
"Wim van Wijk, Klaas van Wijngaarden, Ronald de Witt, Rob Wondergem",
"",
"Luxembourg:",
"Jo‰l Thill, Roland Wenner",
"",
"United Kingdom:",
"Tom Bagshaw, John Charles, Robert Darling, Steven Green, Antony Lacey,",
"Ray Rackham, Kevin Osborne, Arwel Parry, Dale Wright",
"",
"Switzerland:",
"Beat Bucher, Durs Locher, Esther Locher, Hansueli Locher, Res Locher,",
"Manfred Spalinger",
"",
"Italy:",
"Magic.alex Badalic, Massimo Colombo, Ivo Elmi, Alex Guerrazzi,",
"Marco Guerzoni, Claudio Melindi, Ivan Venturi, Marcello Vezzelli",
"",
"France:",
"Dorian Darcourt, Herve Piedvache",
"",
"Austria:",
"Reinhard Wiesler",
"",
"USA:",
"Mike Graham",
"",
"Australia:",
"Ian Mackereth, Gary Spiteri",
"",
"Sweden:",
"Bill Andersson, Kjell Eriksson, Rikard Oesterman",
"",
"Norway:",
"Rolf Sunde",
"",
"=============================================================================",
"  (c) 1990-1997 Stephan Slabihoud, Germany",
"=============================================================================",
NULL
	};
