/* =============================================================== */
/* = šbersetzt Menwahl im Hauptdialog in Buttonauswahl ========== */
int trans_menu(int obj_nr);
int trans_message(void);

/* =============================================================== */
/* = šbersetzt Tastendruck im Hauptdialog #1 ===================== */
int trans_key(int s,int key);

/* =============================================================== */
/* = šbersetzt Tastendruck im "FileAuswahl"-Dialog #9 ============ */
int trans_key1(int shift,int key);

/* =============================================================== */
/* = šbersetzt Tastendruck im "Autopoll"-Dialog #61 ============== */
int trans_key2(int shift,int key);

/* =============================================================== */
/* = šbersetzt Tastendruck im "TimeLeft"-Dialog #19 ============== */
int trans_key3(int shift,int key);

/* =============================================================== */
/* = šbersetzt Tastendruck im "FileRequest"-Dialog #8 ============ */
int trans_key4(int shift,int key);

/* =============================================================== */
/* = šbersetzt Tastendruck im "Hatch"-Dialog #24 ================= */
int trans_key5(int shift,int key);

/* =============================================================== */
/* = šbersetzt Tastendruck im "Areafix"-Dialog #25 =============== */
int trans_key6(int shift,int key);

/* =============================================================== */
