#define AVALONNAME		" AVALON "
#define DTAG					1
#define	DMONAT				11
#define	DJAHR					1996

#if defined( _AVALSEMP_ )
	#define PID						"AVALON 3.90"
	#define VERSION 			"3.90"
	#define HEXVERSION		0x0390
	#define WPSVERSION		"003"
	#define CFGVERSION		"360"
#else
	#define PID						"AVALON 3.90"
	#define VERSION 			"3.90"
	#define HEXVERSION		0x0390
	#define WPSVERSION		"002"
	#define CFGVERSION		"360"
#endif
