/* Resource Datei Indizes fÅr CASIO_SF */

#define DIALOG1          0   /* Formular/Dialog */
#define MAINVERS         1   /* FTEXT in Baum DIALOG1 */
#define EMPFE            2   /* BOXTEXT in Baum DIALOG1 */
#define EMPFK            3   /* BOXTEXT in Baum DIALOG1 */
#define EMPFASCI         4   /* BOXTEXT in Baum DIALOG1 */
#define SENDALL          5   /* BOXTEXT in Baum DIALOG1 */
#define SENDTEL          6   /* BOXTEXT in Baum DIALOG1 */
#define SENDADR          7   /* BOXTEXT in Baum DIALOG1 */
#define SENDTERM         8   /* BOXTEXT in Baum DIALOG1 */
#define SENDBUS          9   /* BOXTEXT in Baum DIALOG1 */
#define SENDMEMO         10  /* BOXTEXT in Baum DIALOG1 */
#define SENDCAL          11  /* BOXTEXT in Baum DIALOG1 */
#define SENDREM          12  /* BOXTEXT in Baum DIALOG1 */
#define SENDREM2         13  /* BOXTEXT in Baum DIALOG1 */
#define EXITPRG          14  /* BOXTEXT in Baum DIALOG1 */
#define REGISTER         15  /* BOXTEXT in Baum DIALOG1 */
#define CONFIGUR         16  /* BOXTEXT in Baum DIALOG1 */

#define DIALOG2          1   /* Formular/Dialog */
#define MARKON           2   /* BUTTON in Baum DIALOG2 */
#define IGNOON           4   /* BUTTON in Baum DIALOG2 */
#define INFOSTAT         5   /* TEXT in Baum DIALOG2 */
#define DATABOX          6   /* BOX in Baum DIALOG2 */
#define LINE1            8   /* STRING in Baum DIALOG2 */
#define LINE2            9   /* STRING in Baum DIALOG2 */
#define LINE3            10  /* STRING in Baum DIALOG2 */
#define LINE4            11  /* STRING in Baum DIALOG2 */
#define LINE5            12  /* STRING in Baum DIALOG2 */
#define LINE6            13  /* STRING in Baum DIALOG2 */
#define LINE7            14  /* STRING in Baum DIALOG2 */
#define LINE8            15  /* STRING in Baum DIALOG2 */
#define LINE9            16  /* STRING in Baum DIALOG2 */
#define IMP4             18  /* BOXCHAR in Baum DIALOG2 */
#define IMP5             19  /* BOXCHAR in Baum DIALOG2 */
#define IMP6             20  /* BOXCHAR in Baum DIALOG2 */
#define IMP7             21  /* BOXCHAR in Baum DIALOG2 */
#define IMP8             22  /* BOXCHAR in Baum DIALOG2 */
#define IMP9             23  /* BOXCHAR in Baum DIALOG2 */
#define LINEEXIT         24  /* BUTTON in Baum DIALOG2 */
#define LINELOOK         25  /* BUTTON in Baum DIALOG2 */
#define LINERUN          26  /* BUTTON in Baum DIALOG2 */
#define LINECONT         27  /* BUTTON in Baum DIALOG2 */
#define LINESEND         28  /* BUTTON in Baum DIALOG2 */

#define DIALOG3          2   /* Formular/Dialog */
#define INFOLINE         1   /* TEXT in Baum DIALOG3 */
#define DATAITEM         2   /* FTEXT in Baum DIALOG3 */

#define DIALOG4          3   /* Formular/Dialog */
#define SEARCH           1   /* FTEXT in Baum DIALOG4 */
#define SEARCHOK         2   /* BUTTON in Baum DIALOG4 */

#define DIALOG5          4   /* Formular/Dialog */
#define SDATUM           1   /* FTEXT in Baum DIALOG5 */
#define SMARKON          3   /* BUTTON in Baum DIALOG5 */
#define SZEIT            4   /* FTEXT in Baum DIALOG5 */
#define SALARM           5   /* FTEXT in Baum DIALOG5 */
#define STEXT1           6   /* FTEXT in Baum DIALOG5 */
#define STEXT2           7   /* FTEXT in Baum DIALOG5 */
#define STEXT3           8   /* FTEXT in Baum DIALOG5 */
#define SEXIT            10  /* BUTTON in Baum DIALOG5 */
#define SSEND            11  /* BUTTON in Baum DIALOG5 */
#define TAG1             14  /* FTEXT in Baum DIALOG5 */
#define TAG2             15  /* FTEXT in Baum DIALOG5 */
#define TAG3             16  /* FTEXT in Baum DIALOG5 */
#define TAG4             17  /* FTEXT in Baum DIALOG5 */
#define TAG5             18  /* FTEXT in Baum DIALOG5 */
#define TAG6             19  /* FTEXT in Baum DIALOG5 */
#define TAG7             20  /* FTEXT in Baum DIALOG5 */
#define TAG8             21  /* FTEXT in Baum DIALOG5 */
#define TAG9             22  /* FTEXT in Baum DIALOG5 */
#define TAG10            23  /* FTEXT in Baum DIALOG5 */
#define TAG11            24  /* FTEXT in Baum DIALOG5 */
#define TAG12            25  /* FTEXT in Baum DIALOG5 */
#define TAG13            26  /* FTEXT in Baum DIALOG5 */
#define TAG14            27  /* FTEXT in Baum DIALOG5 */
#define TAG15            28  /* FTEXT in Baum DIALOG5 */
#define TAG16            29  /* FTEXT in Baum DIALOG5 */

#define DIALOG6          5   /* Formular/Dialog */
#define MMARKON          2   /* BUTTON in Baum DIALOG6 */
#define MBOX             3   /* IBOX in Baum DIALOG6 */
#define MTEXT1           4   /* FTEXT in Baum DIALOG6 */
#define MTEXT2           5   /* FTEXT in Baum DIALOG6 */
#define MTEXT3           6   /* FTEXT in Baum DIALOG6 */
#define MTEXT4           7   /* FTEXT in Baum DIALOG6 */
#define MTEXT5           8   /* FTEXT in Baum DIALOG6 */
#define MTEXT6           9   /* FTEXT in Baum DIALOG6 */
#define MTEXT7           10  /* FTEXT in Baum DIALOG6 */
#define MTEXT8           11  /* FTEXT in Baum DIALOG6 */
#define MTEXT9           12  /* FTEXT in Baum DIALOG6 */
#define MTEXT10          13  /* FTEXT in Baum DIALOG6 */
#define MTEXT11          14  /* FTEXT in Baum DIALOG6 */
#define MTEXT12          15  /* FTEXT in Baum DIALOG6 */
#define MEXIT            17  /* BUTTON in Baum DIALOG6 */
#define MLOAD            18  /* BUTTON in Baum DIALOG6 */
#define MSEND            19  /* BUTTON in Baum DIALOG6 */

#define DIALOG7          6   /* Formular/Dialog */
#define BNAME            1   /* FTEXT in Baum DIALOG7 */
#define BFIRMA           2   /* FTEXT in Baum DIALOG7 */
#define BTEL             3   /* FTEXT in Baum DIALOG7 */
#define BPOS             4   /* FTEXT in Baum DIALOG7 */
#define BABT             5   /* FTEXT in Baum DIALOG7 */
#define BPOST            6   /* FTEXT in Baum DIALOG7 */
#define BADR             7   /* FTEXT in Baum DIALOG7 */
#define BTELEX           8   /* FTEXT in Baum DIALOG7 */
#define BFAX             9   /* FTEXT in Baum DIALOG7 */
#define BFREI1           10  /* FTEXT in Baum DIALOG7 */
#define BFREI2           11  /* FTEXT in Baum DIALOG7 */
#define BFREI3           12  /* FTEXT in Baum DIALOG7 */
#define BFREI4           13  /* FTEXT in Baum DIALOG7 */
#define BFREI5           14  /* FTEXT in Baum DIALOG7 */
#define BFREI6           15  /* FTEXT in Baum DIALOG7 */
#define BEXIT            16  /* BUTTON in Baum DIALOG7 */
#define BMARKON          18  /* BUTTON in Baum DIALOG7 */
#define BSEND            19  /* BUTTON in Baum DIALOG7 */

#define DIALOG8          7   /* Formular/Dialog */
#define ANAME            1   /* FTEXT in Baum DIALOG8 */
#define ATEL             2   /* FTEXT in Baum DIALOG8 */
#define AADR             3   /* FTEXT in Baum DIALOG8 */
#define AFREI1           4   /* FTEXT in Baum DIALOG8 */
#define AFREI2           5   /* FTEXT in Baum DIALOG8 */
#define AFREI3           6   /* FTEXT in Baum DIALOG8 */
#define AFREI4           7   /* FTEXT in Baum DIALOG8 */
#define AFREI5           8   /* FTEXT in Baum DIALOG8 */
#define AFREI6           9   /* FTEXT in Baum DIALOG8 */
#define AEXIT            10  /* BUTTON in Baum DIALOG8 */
#define AMARKON          12  /* BUTTON in Baum DIALOG8 */
#define ASEND            13  /* BUTTON in Baum DIALOG8 */

#define DIALOG9          8   /* Formular/Dialog */
#define CDATUM           1   /* FTEXT in Baum DIALOG9 */
#define CBOX             2   /* IBOX in Baum DIALOG9 */
#define C1               3   /* BOXTEXT in Baum DIALOG9 */
#define CEXIT            34  /* BUTTON in Baum DIALOG9 */
#define CSEND            35  /* BUTTON in Baum DIALOG9 */

#define DIALOG10         9   /* Formular/Dialog */
#define REGINFO          1   /* BOXTEXT in Baum DIALOG10 */
#define REGNAME          2   /* FTEXT in Baum DIALOG10 */
#define REGKEY           3   /* FTEXT in Baum DIALOG10 */
#define REGSAVE          4   /* BUTTON in Baum DIALOG10 */
#define REGEXIT          5   /* BUTTON in Baum DIALOG10 */

#define DIALOG11         10  /* Formular/Dialog */
#define E1200            3   /* BOXTEXT in Baum DIALOG11 */
#define E2400            4   /* BOXTEXT in Baum DIALOG11 */
#define E4800            5   /* BOXTEXT in Baum DIALOG11 */
#define E9600            6   /* BOXTEXT in Baum DIALOG11 */
#define E19200           7   /* BOXTEXT in Baum DIALOG11 */
#define S1200            10  /* BOXTEXT in Baum DIALOG11 */
#define S2400            11  /* BOXTEXT in Baum DIALOG11 */
#define S4800            12  /* BOXTEXT in Baum DIALOG11 */
#define S9600            13  /* BOXTEXT in Baum DIALOG11 */
#define S19200           14  /* BOXTEXT in Baum DIALOG11 */
#define PORT0            17  /* BOXTEXT in Baum DIALOG11 */
#define PORT1            18  /* BOXTEXT in Baum DIALOG11 */
#define PORT2            19  /* BOXTEXT in Baum DIALOG11 */
#define PORT3            20  /* BOXTEXT in Baum DIALOG11 */
#define PORT4            21  /* BOXTEXT in Baum DIALOG11 */
#define SUMLAUTE         23  /* BOXTEXT in Baum DIALOG11 */
#define CSAVE            24  /* BUTTON in Baum DIALOG11 */
#define COK              25  /* BUTTON in Baum DIALOG11 */

#define DIALOG12         11  /* Formular/Dialog */
#define RDATUM           1   /* FTEXT in Baum DIALOG12 */
#define RMARKON          3   /* BUTTON in Baum DIALOG12 */
#define RALARM           7   /* FTEXT in Baum DIALOG12 */
#define RTEXT1           8   /* FTEXT in Baum DIALOG12 */
#define RTEXT2           9   /* FTEXT in Baum DIALOG12 */
#define RTEXT3           10  /* FTEXT in Baum DIALOG12 */
#define REXIT            12  /* BUTTON in Baum DIALOG12 */
#define RSEND            13  /* BUTTON in Baum DIALOG12 */

#define DIALOG13         12  /* Formular/Dialog */
#define REM2VON          1   /* FTEXT in Baum DIALOG13 */
#define REM2MARK         3   /* BUTTON in Baum DIALOG13 */
#define REM2BIS          4   /* FTEXT in Baum DIALOG13 */
#define REM2ZEIT         5   /* FTEXT in Baum DIALOG13 */
#define REM2ALAR         6   /* FTEXT in Baum DIALOG13 */
#define REM2YEAR         8   /* BUTTON in Baum DIALOG13 */
#define REM2MONT         9   /* BUTTON in Baum DIALOG13 */
#define REM2WEEK         10  /* BUTTON in Baum DIALOG13 */
#define REM2DAY          11  /* BUTTON in Baum DIALOG13 */
#define REM2WORK         12  /* BUTTON in Baum DIALOG13 */
#define REM2FEST         13  /* BUTTON in Baum DIALOG13 */
#define REM2TXT1         14  /* FTEXT in Baum DIALOG13 */
#define REM2TXT2         15  /* FTEXT in Baum DIALOG13 */
#define REM2TXT3         16  /* FTEXT in Baum DIALOG13 */
#define REM2EXIT         18  /* BUTTON in Baum DIALOG13 */
#define REM2SEND         19  /* BUTTON in Baum DIALOG13 */

#define DIALOG99         13  /* Formular/Dialog */
#define ICFSPIC          1   /* IMAGE in Baum DIALOG99 */

#define PICTURE0         14  /* Formular/Dialog */
#define ICFS0            1   /* IMAGE in Baum PICTURE0 */
#define ICFS1            2   /* IMAGE in Baum PICTURE0 */
